# Generated by Django 4.2 on 2024-05-21 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MiprimerABM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default='2024-01-01')),
                ('descripcion', models.TextField(default='Descripción de la compra', max_length=1000)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'compra',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(default='Permiso', max_length=100)),
                ('descripcion', models.CharField(default='Descripción del permiso', max_length=1000)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'Permiso',
            },
        ),
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name': 'Direccion', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'verbose_name': 'Localidad', 'verbose_name_plural': 'Localidades'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.RemoveField(
            model_name='direccion',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='nombre',
        ),
        migrations.AddField(
            model_name='localidad',
            name='cod_postal',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='localidad',
            name='nombre_localidad',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='valor por defecto', max_length=255),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(default='nombre por defecto', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(default='Desconocido', max_length=50),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='direccion',
            table='direccion',
        ),
        migrations.AlterModelTable(
            name='localidad',
            table='localidad',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='rol',
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('apellido', models.CharField(default='Apellido', max_length=50)),
                ('nombre', models.CharField(default='Nombre', max_length=50)),
                ('email', models.CharField(default='email@example.com', max_length=50)),
                ('telefono', models.CharField(default='123456789', max_length=50)),
                ('clave_usuario', models.CharField(default='clave', max_length=50)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiprimerABM.direccion')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiprimerABM.rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Rol_Permiso',
            fields=[
                ('id_rol_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('id_permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiprimerABM.permiso')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiprimerABM.rol')),
            ],
            options={
                'verbose_name': 'Rol_Permiso',
                'verbose_name_plural': 'Rol_Permisos',
                'db_table': 'Rol_Permiso',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_pedido', models.DateField(default='2024-01-01')),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiprimerABM.usuario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_calculado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiprimerABM.compra')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiprimerABM.producto')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
                'db_table': 'detalle',
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiprimerABM.usuario'),
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id_barrio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_barrio', models.CharField(default='Desconocido', max_length=50)),
                ('id_localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiprimerABM.localidad')),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
                'db_table': 'barrio',
            },
        ),
        migrations.AlterField(
            model_name='direccion',
            name='id_barrio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiprimerABM.barrio'),
        ),
    ]
